language: node_js
node_js:
  - 12
addons:
  packages:
    - libgconf-2-4
script:
  - npx lint-staged
  - npm run test:coveralls
  - npm run test:cypress:ci
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: react-web-app-dsn
notifications:
  email: false